insert into category_type(id,name,description )
values (1,'شگفت انگیز','شگفت انگیز');

insert into category_type(id,name,description )
values (2,'خرید عمده','خرید عمده');

insert into category_type(id,name,description )
values (3,'هدیه','هدیه');

insert into category_type(id,name,description )
values (4,'جستجو','جستجو');

insert into category_type(id,name,description )
values (5,'کاتالوگ','کاتالوگ');

insert into category_type(id,name,description )
values (6,'سایت همکار','سایت همکار');

insert into category_type(id,name,description )
values (7,'content','content');

insert into category_type(id,name,description )
values (8,'product','product');

insert into category_type(id,name,description)
values (9,'menus','menus');
