insert into category_type(id,name,description )
value (1,'شگفت انگیز','شگفت انگیز');

insert into category_type(id,name,description )
value (2,'خرید عمده','خرید عمده');

insert into category_type(id,name,description )
value (3,'هدیه','هدیه');

insert into category_type(id,name,description )
value (4,'جستجو','جستجو');

insert into category_type(id,name,description )
value (5,'کاتالوگ','کاتالوگ');

insert into category_type(id,name,description )
value (6,'سایت همکار','سایت همکار');

insert into category_type(id,name,description )
value (7,'content','content');

insert into category_type(id,name,description )
value (8,'product','product');

insert into category_type(id,name,description)
values (9,'menus','menus');
